src/Presentacion/EscuelaNet.Presentacion.Clientes.web/Controllers/SolicitudesController.cs
using EscuelaNet.Dominio.Clientes;
using EscuelaNet.Presentacion.Clientes.Web.Infraestructura;
using EscuelaNet.Presentacion.Clientes.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Clientes.Web.Controllers
{
    public class SolicitudesController : Controller
    {
        
        public ActionResult Index(int idCliente, int idUnidad)
        {
            var cliente = Contexto.Instancia.Clientes[idCliente];
            var unidad = cliente.Unidades[idUnidad];

            if (unidad.Solicitudes == null)
            {
                TempData["error"] = "Unidad sin solicitudes";
                return RedirectToAction("../unidades/Index/"+idCliente);
            }

            var solicitudes = unidad.Solicitudes;

            List<Solicitud> solic = new List<Solicitud>();                      
            
            foreach (var solicitud in solicitudes)
            {
                solic.Add(solicitud);
            }
            
            var model = new SolicitudesIndexModel()
            {
                Titulo = "Solicitudes de la Unidad '"+unidad.RazonSocial+ "' del Cliente '"+cliente.RazonSocial+"'",
                IdCliente = idCliente,
                IdUnidad = idUnidad,
                Solicitudes = solic
            };

            return View(model);
        }


        public ActionResult New(int idCliente, int idUnidad)
        {
            var cliente = Contexto.Instancia.Clientes[idCliente];
            var unidad = cliente.Unidades[idUnidad];
            var model = new NuevaSolicitudModel() {
                Titul= "Nueva Solicitud para la Unidad '"+unidad.RazonSocial+"' del Cliente '"+cliente.RazonSocial+"'",
                IdC = idCliente,
                IdU = idUnidad
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult New(NuevaSolicitudModel model)
        {
            if (!string.IsNullOrEmpty(model.Titulo))
            {
                try
                {
                    Contexto.Instancia.Clientes[model.IdC].Unidades[model.IdU].AgregarSolicitud(new Solicitud(model.Titulo, model.Descripcion));
                    TempData["success"] = "Solicitud creada";                   
                    return RedirectToAction("Index", new { idCliente = model.IdC, idUnidad = model.IdU });

                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }

            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);
            }
        }

        public ActionResult Edit(int idCliente, int idUnidad, int idSolic)
        {
            var cantidad = Contexto.Instancia.Clientes.Count();
            if (idCliente < 0 || idCliente >= cantidad)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("Index", new { idCliente =idCliente, idUnidad = idUnidad });
            }
            else
            {
                var cliente = Contexto.Instancia.Clientes[idCliente];
                var unidad = cliente.Unidades[idUnidad];
                var solicitud = unidad.Solicitudes[idSolic];

                var model = new NuevaSolicitudModel()
                {
                    Titul = "Editar la Solicitud '"+solicitud.Titulo+"' de la Unidad '" + unidad.RazonSocial + "' del Cliente '" + cliente.RazonSocial + "'",
                    IdC = idCliente,
                    IdU = idUnidad,
                    IdS = idSolic,
                    Titulo = solicitud.Titulo,
                    Descripcion = solicitud.Descripcion,
                    Estado = solicitud.Estado,
                };

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Edit(NuevaSolicitudModel model)
        {
            if (!string.IsNullOrEmpty(model.Titulo))
            {
                try
                {
                    Contexto.Instancia.Clientes[model.IdC].Unidades[model.IdU].Solicitudes[model.IdS].Titulo = model.Titulo;
                    Contexto.Instancia.Clientes[model.IdC].Unidades[model.IdU].Solicitudes[model.IdS].Descripcion = model.Descripcion;
                    Contexto.Instancia.Clientes[model.IdC].Unidades[model.IdU].Solicitudes[model.IdS].CambiarEstado( model.Estado);

                    TempData["success"] = "Solicitud editada";
                    return RedirectToAction("Index", new { idCliente = model.IdC, idUnidad = model.IdU });
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }

            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);
            }
        }

        public ActionResult Delete(int idCliente, int idUnidad, int idSolic)
        {
            var cantidad = Contexto.Instancia.Clientes.Count();
            if (idCliente < 0 || idCliente >= cantidad)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("Index", new { idCliente = idCliente, idUnidad = idUnidad });
            }
            else
            {
                var cliente = Contexto.Instancia.Clientes[idCliente];
                var unidad = cliente.Unidades[idUnidad];
                var solicitud = unidad.Solicitudes[idSolic];

                var model = new NuevaSolicitudModel()
                {
                    IdC = idCliente,
                    IdU = idUnidad,
                    IdS = idSolic,
                    Titulo = solicitud.Titulo,
                    Descripcion = solicitud.Descripcion,
                    Estado = solicitud.Estado,
                };

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Delete(NuevaSolicitudModel model)
        {

            try
            {
                Contexto.Instancia.Clientes[model.IdC].Unidades[model.IdU].Solicitudes.RemoveAt(model.IdS);
                TempData["success"] = "Solicitud borrada";
                return RedirectToAction("Index", new { idCliente = model.IdC, idUnidad = model.IdU });
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }

        }

    }
}

src/Presentacion/EscuelaNet.Presentacion.Clientes.web/Views/Solicitudes/Edit.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.NuevaSolicitudModel

@{
    ViewBag.Title = "Editar";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.Titul</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Edit", "Solicitudes", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdC)
                @Html.HiddenFor(model => model.IdU)
                @Html.HiddenFor(model => model.IdS)
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Titulo" } })
                        @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Descripción" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EnumDropDownListFor(model => model.Estado, htmlAttributes: new { @class = "form-control col-md-2" })
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="~/solicitudes/index/?idCliente=@Model.IdC&idUnidad=@Model.IdU" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });

    </script>

}

src/Presentacion/EscuelaNet.Presentacion.Clientes.web/Views/Solicitudes/Index.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.SolicitudesIndexModel
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-5">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.Titulo</h3>
                <label class="text-success">@TempData["success"]</label>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>

                            <th style="width: 10px">#</th>
                            <th>Titulo</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                        @Html.HiddenFor(model => model.IdCliente)
                        @Html.HiddenFor(model => model.IdUnidad)
                        @foreach (var solicitud in Model.Solicitudes)
                        {
                            <tr>


                                <td>@Model.Solicitudes.IndexOf(solicitud)</td>
                                <td>@solicitud.Titulo</td>
                                <td>@solicitud.Descripcion</td>
                                <td>@solicitud.Estado</td>

                                <td>
                                    <a href="/Solicitudes/edit/?idCliente=@Model.IdCliente&idUnidad=@Model.IdUnidad&idSolic=@Model.Solicitudes.IndexOf(solicitud)" title="Editar" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                                    </a>
                                    <a href="/Solicitudes/delete/?idCliente=@Model.IdCliente&idUnidad=@Model.IdUnidad&idSolic=@Model.Solicitudes.IndexOf(solicitud)" title="Borrar" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-remove"></i> Borrar</label>
                                    </a>
                                </td>

                            </tr>
                        }


                        <tr>
                            <td colspan="6">
                                <a href="/solicitudes/new/?idCliente=@Model.IdCliente&idUnidad=@Model.IdUnidad" title="Nuevo" class="btn btn-toolbar">
                                    <label class="label bg-gray"><i class="fa fa-plus"></i> Nuevo</label>
                                </a>
                            </td>

                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- /.box -->
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
</div>


<div>
    @Html.ActionLink("Volver a Unidades", "../Unidades/Index/", new {id = Model.IdCliente })
</div>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Clientes.web/Views/Solicitudes/New.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.NuevaSolicitudModel

@{
    ViewBag.Title = "New";
}

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@Model.Titul</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("New", "Solicitudes", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdC)
                    @Html.HiddenFor(model => model.IdU)
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Titulo" } })
                            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Descripcion" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            <div class="help-block with-errors"></div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EnumDropDownListFor(model => model.Estado, htmlAttributes: new { @class = "form-control col-md-2" })
                        </div>*@
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a href="~/solicitudes/index/?idCliente=@Model.IdC&idUnidad=@Model.IdU" class="btn btn-primary">Cancelar</a>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

@section Scripts {
  <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
  <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });
     
  </script>

}