src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Controllers/ProyectosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EscuelaNet.Presentacion.Proyectos.Web.Infraestructura;
using EscuelaNet.Presentacion.Proyectos.Web.Models;
using EscuelaNet.Dominio.Proyectos;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class ProyectosController : Controller
    {
        // GET: Proyectos
        public ActionResult Index(int id)
        {
            var linea = Contexto.Instancia.LineasDeProduccion[id];
            var model = new ProyectoIndexModel();
          
            model.Titulo = string.Format("Proyecto de {0}", linea.Nombre);
            model.Proyectos = (List<Proyecto>)linea.Proyectos;
            model.Linea = id;
            return View(model);
        }

        public ActionResult New()
        {
            var model = new NuevoProyectoModel();
            return View(model);
        }

        [HttpPost]

        public ActionResult New(NuevoProyectoModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].pushProyecto(
                        model.Nombre, model.Descripcion, model.NombreResponsable, model.TelefonoResponsable, model.EmailResponsable
                        );
                    TempData["success"] = "Proyecto creado";
                    return RedirectToAction("Index/"+model.IDLinea);
                }catch(Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);
            }
        }

        public ActionResult Edit(int idProy, int idLinea)
        {

            var proyecto = Contexto.Instancia.LineasDeProduccion[idLinea].Proyectos[idProy];
            var model = new NuevoProyectoModel()
            {
                Nombre = proyecto.Nombre,
                Id = idProy,
                Descripcion = proyecto.Descripcion,
                NombreResponsable = proyecto.NombreResponsable,
                TelefonoResponsable = proyecto.TelefonoResponsable,
                EmailResponsable = proyecto.EmailResponsable,
                IDLinea = idLinea
            };
            return View(model);
        }

        [HttpPost]

        public ActionResult Edit(NuevoProyectoModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre) || !string.IsNullOrEmpty(model.Descripcion))
            {
                try
                {
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.Id].Nombre = model.Nombre;
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.Id].Descripcion = model.Descripcion;
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.Id].NombreResponsable = model.NombreResponsable;
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.Id].TelefonoResponsable = model.TelefonoResponsable;
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.Id].EmailResponsable = model.EmailResponsable;

                    TempData["success"] = "Proyecto modificado";
                    return RedirectToAction("Index", new { id= model.IDLinea });
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Se pasó un nombre o descripcion vacio/erroneo.";
                return View(model);
            }
        }

    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Proyectos/Delete.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevoProyectoModel

@{
    ViewBag.Title = "Borrar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Borrar proyecto</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="box-body">
                        <p>
                            ¿Está seguro de borrar el proyecto "@Model.Nombre"?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Volver a la lista de proyectos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Proyectos/Edit.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevoProyectoModel

@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo proyectos</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.IDLinea)
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Este campo es obligatorio.", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Este campo es obligatorio.", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.NombreResponsable, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.NombreResponsable, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NombreResponsable, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TelefonoResponsable, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.TelefonoResponsable, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TelefonoResponsable, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailResponsable, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.EmailResponsable, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EmailResponsable, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </div>
                    <div class="box-footer">
                        <a href="/Home/Index">Cancelar</a>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Proyectos/Index.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.ProyectoIndexModel

@{
    ViewBag.Title = "Index";
    var x = 1;
    for (var i = 10; i > 0; i--)
    {
        x *= i;
    }
}

<div class="row">
        <div class="col-md-6">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Proyectos</h3>
                <label class="text-success">@TempData["success"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <th style="width: 10px">#</th>
                          <th>Título</th>
                          <th>Acciones</th>
                      </tr>                      
                      <p>@Model.Linea</p>
                      @foreach (var proyectos in Model.Proyectos)
                      {
                          <tr>
                              <td>@Model.Proyectos.IndexOf(proyectos)</td>
                              <td>@proyectos.Nombre</td>
                              <td>
                                  <a href="/Proyectos/edit/?idProy=@Model.Proyectos.IndexOf(proyectos)&idLinea=@Model.Linea" title="Editar" class="btn btn-toolbar">
   <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                                  </a>
                                  <a href="/Proyectos/delete/@Model.Proyectos.IndexOf(proyectos)" title="borrar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-remove"></i> Borrar</label>
                                  </a>
                              </td>
                          </tr>

                      }
                      <tr>
                          <td></td>
                          <td></td>
                          <td>
                              <a href="/Proyectos/New" title="Nuevo" class="btn btn-toolbar">
                                  <label class="label bg-gray"><i class="fa fa-plus"></i> Nuevo</label>
                              </a>
                          </td>
                      </tr>
                  </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
              </ul>
            </div>
          </div>
          <!-- /.box -->

          <!-- /.box -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
      </div></p>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Proyectos/New.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevoProyectoModel

@{
    ViewBag.Title = "New";
}




    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo proyecto</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("New", "Proyectos", null,
                           FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IDLinea)

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el nombre de la linea.", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar la descripción del proyecto", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.NombreResponsable, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.NombreResponsable, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el nombre del responsable.", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.NombreResponsable, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TelefonoResponsable, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.TelefonoResponsable, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el telefono del responsable.", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.TelefonoResponsable, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailResponsable, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.EmailResponsable, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el email del responsable.", data_minlength = "9" } })
                            @Html.ValidationMessageFor(model => model.EmailResponsable, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
        $(document).ready(function () {
            $('#myForm').validator()
        });
    </script>
}