src/Presentacion/EscuelaNet.Presentacion.Capacitacion.Web/Controllers/TemasController.cs
using EscuelaNet.Dominio.Capacitaciones;
using EscuelaNet.Presentacion.Capacitacion.Web.Infraestructura;
using EscuelaNet.Presentacion.Capacitacion.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Capacitacion.Web.Controllers
{
    public class TemasController : Controller
    {
        // GET: Tema
        public ActionResult Index()
        {
            var temas = ContextoTema.Instancia.Temas;
            var model = new TemaIndexModel()
            {
                Titulo = "Primera prueba",
                Temas = temas
            };
            return View(model);
        }

        // GET: Tema/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Tema/New
        public ActionResult New()
        {
            var model = new NuevoTemaModel();
            return View(model);
        }

        // POST: Tema/New
        [HttpPost]
        public ActionResult New(NuevoTemaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    ContextoTema.Instancia.Temas.Add(new Tema(model.Nombre, model.Nivel));

                    TempData["success"] = "Tema creado";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);

            }
        }

        // GET: Tema/Edit/5
        public ActionResult Edit(int id)
        {
            var tema = ContextoTema.Instancia.Temas[id];
            var model = new NuevoTemaModel()
            {
                Nombre = tema.Nombre,
                Id = id,
                Nivel = tema.Nivel
            };
            return View(model);
        }

        // POST: Tema2/Edit/5
        [HttpPost]
        public ActionResult Edit(NuevoTemaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                        try
                        {
                            ContextoTema.Instancia.Temas[model.Id].Nombre
                                = model.Nombre;
                            ContextoTema.Instancia.Temas[model.Id].Nivel
                                = model.Nivel;

                            TempData["success"] = "Tema Editado";
                            return RedirectToAction("Index");
                        }
                            catch (Exception ex)
                        {
                            TempData["error"] = ex.Message;
                            return View(model);
                        }
            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);

            }

        }

        // GET: Tema/Delete/5
        public ActionResult Delete(int id)
        {
            var tema = ContextoTema.Instancia.Temas[id];
            var model = new NuevoTemaModel()
            {
                Nombre = tema.Nombre,
                Id = id,
                Nivel = tema.Nivel,
            };
            return View(model);
        }

        // POST: Tema/Delete/5
        [HttpPost]
        public ActionResult Delete(NuevoTemaModel model)
        {
            try
            {
                ContextoTema.Instancia.Temas.RemoveAt(model.Id);
                TempData["success"] = "Tema borrado";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Capacitacion.Web/Views/Temas/Delete.cshtml
@model EscuelaNet.Presentacion.Capacitacion.Web.Models.NuevoTemaModel

@{
    ViewBag.Title = "Delete";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Borrar Tema</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model=>model.Id)
                <div class="box-body">
                    <p>
                        ¿Tema a Borrar: "@Model.Nombre"?
                    </p>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="~/temas/" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Capacitacion.Web/Views/Temas/Edit.cshtml
@model EscuelaNet.Presentacion.Capacitacion.Web.Models.NuevoTemaModel

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Editar Tema</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Edit", "Temas", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Nombre" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EnumDropDownListFor(model => model.Nivel, htmlAttributes: new { @class = "form-control col-md-2" })
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="~/temas/" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });

    </script>

}

src/Presentacion/EscuelaNet.Presentacion.Capacitacion.Web/Views/Temas/Index.cshtml
@model EscuelaNet.Presentacion.Capacitacion.Web.Models.TemaIndexModel
@{
    ViewBag.Title = "Index";
    var x = 1;
    for (var i = 10; i > 0; i--)
    {
        x *= i;
    }
}
<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Temas     -</h3>
                
                <label class="text-success">@TempData["success"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Nombre</th>
                            <th>Nivel</th>
                        </tr>
                        @foreach (var tema in Model.Temas)
                        {
                            <tr>
                                <td>@Model.Temas.IndexOf(tema)</td>
                                <td>@tema.Nombre</td>
                                <td>@tema.Nivel</td>

                                <td>
                                    <a href="/Temas/edit/@Model.Temas.IndexOf(tema)" title="Editar" class="btn btn-primary">
                                        Editar
                                    </a>
                                    <a href="/Temas/delete/@Model.Temas.IndexOf(tema)" title="borrar" class="btn btn-danger">
                                        Borrar
                                    </a>
                                </td>
                            </tr>

                        }
                        <tr>
                            <td></td>
                            <td></td>
                            <td>
                                <a href="/Temas/new" title="Nuevo" class="btn btn-primary">
                                    Nuevo
                                </a>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- /.box -->
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
</div>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Capacitacion.Web/Views/Temas/New.cshtml
@model EscuelaNet.Presentacion.Capacitacion.Web.Models.NuevoTemaModel

@{
    ViewBag.Title = "New";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Nuevo Tema</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("New", "Temas", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el Campo" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EnumDropDownListFor(model => model.Nivel, htmlAttributes: new { @class = "form-control col-md-2" })
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="~/temas/" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });

    </script>

}